### ISSUE TITLE
Buildcraft Diamond Transport Pipe

### ISSUE THREAD

**Issue by The-Order** [F32Organization/Faithful32-1.7.10#100]
With a recent update the diamond item transport pipe is now broken.

**Comment by DZCreeper** [comment]
What BuildCraft version are you using?

**Comment by The-Order** [comment]
Buildcraft 6.2.6. Sorry, I forgot it recently updated and I can't update my modpack yet. Not sure what happens in newer version.

**Comment by DZCreeper** [comment]
With BC 6.3.3 the pipe renders correctly when placed but not when held in inventory. Is this the same for you?

**Comment by The-Order** [comment]
Yeah, that's the same issue I was seeing after just testing it. Not sure why.
