### ISSUE TITLE
Tinkers Brownstone

### ISSUE THREAD

**Issue by The-Order** [F32Organization/Faithful32-1.7.10#101]
I did a few textures for Tinkers Construct Brownstone.

https://drive.google.com/file/d/0B0XbQ0OpHz_3NXM0UlQzQnFPdlE/view?usp=sharing

**Comment by DZCreeper** [comment]
https://github.com/F32Organization/Faithful32-1.7.10/commit/dc89ce54dc1b8ead5f2aacd623f7b1d57057ffcd
