### ISSUE TITLE
[Not really an issue] Version notes 

### ISSUE THREAD

**Issue by Jules-2K** [F32Organization/Faithful32-1.7.10#111]
Hi, is it possible to put version numbers or a changelog for the F32 ?
I like to regularly check if there is an update.
Thanks :D

**Comment by DZCreeper** [comment]
Would you prefer a manual changelog in a .txt file or have a list of Github commits displayed on the website automatically?

**Comment by Jules-2K** [comment]
A thing on the website would be great, thanks a lot ! :)

**Comment by DZCreeper** [comment]
https://github.com/F32Organization/siteF32/commit/08c08851c3711c36eba2d95dbedcdec8416dd9a8 added the last 5 commits to the main page. Let me know if you had something different in mind.

**Comment by stephenmc608** [comment]
That looks fantastic! And it's super-useful too! Thanks! :D

**Comment by Xee1** [comment]
Very good thing!

**Comment by Jules-2K** [comment]
Perfect ! Thanks
