### ISSUE TITLE
Thermal Expansion Fluid Transposer

### ISSUE THREAD

**Issue by stephenmc608** [F32Organization/Faithful32-1.7.10#121]
I noticed that the input (The Blue) area was a little off.

![2015-02-27_03 29 27](https://cloud.githubusercontent.com/assets/8429816/6409375/fe0f356a-be30-11e4-91e3-7736f2c4fc67.png)
![2015-02-27_03 29 32](https://cloud.githubusercontent.com/assets/8429816/6409377/fe12ad4e-be30-11e4-9cbb-9c9b65d1a463.png)
![2015-02-27_03 29 35](https://cloud.githubusercontent.com/assets/8429816/6409376/fe112b5e-be30-11e4-9ea9-6b534999d918.png)

**Comment by DZCreeper** [comment]
What resolution are you playing at? This seems to be a scaling issue because at 1920x1080 there is no problem.

**Comment by stephenmc608** [comment]
I'm playing at 1920x1080, with the large GUI scale selected.

**Comment by DZCreeper** [comment]
I normally use the auto GUI scale which for 1920x1080 defaults to Extra Large, hence why I haven't noticed the scaling issues. Unfortunately there is nothing I can really do to fix the issue, its just some textures are at a size where scaling them to non-multiple sizes looks terrible.

**Comment by stephenmc608** [comment]
Alright. Thanks for the help.
