### ISSUE TITLE
Do : TiCon new Thermal Foundation parts

### ISSUE THREAD

**Issue by Jules06** [F32Organization/Faithful32-1.7.10#123]
Thanks !

**Comment by DZCreeper** [comment]
I assume you mean the Electrum and Shiny tools and parts? That is actually controlled by a new hex color system from TiC. Some of the templates that it uses have been completed, others aren't.

**Comment by Adaptivity** [comment]
@DZCreeper Tcon Weaponry now fully supported. Can be closed.
