### ISSUE TITLE
[Bug] Simply jetpack

### ISSUE THREAD

**Issue by MrBretze** [F32Organization/Faithful32-1.7.10#127]
http://puu.sh/gn1rV/4b927d62b5.jpg 3D jet pack not found ><

**Comment by fewizz** [comment]
hehe

**Comment by DZCreeper** [comment]
Wow, SimplyJetpacks support is way out of date. I will get around to it eventually, got a couple things ahead of it though. Just cleaned up the folder enough to get what small amount of support we do have to work again.
