### ISSUE TITLE
Missing Mekanism Machines

### ISSUE THREAD

**Issue by infogulch** [F32Organization/Faithful32-1.7.10#139]
The Mekanism machines have no 32x32 texture. Is adding textures for them on the radar?

**Comment by DZCreeper** [comment]
Can you take a screenshot for me? I thought Mekanism machines were 32x32 by default.

**Comment by infogulch** [comment]
Oh, you're right. Sorry for the trouble. :astonished:

Here are a few of the assets. Yep they're 32px wide. :straight_ruler:
![basicfactoryfront](https://cloud.githubusercontent.com/assets/133882/6600637/cdb9a672-c7de-11e4-88f9-d94dc18be54d.png)
![precisionsawmillfronton](https://cloud.githubusercontent.com/assets/133882/6600639/cdbef4a6-c7de-11e4-961c-4efcff0cb491.png)
