### ISSUE TITLE
Thermal Foundation material colors doesn't respect vanilla

### ISSUE THREAD

**Issue by Adaptivity** [F32Organization/Faithful32-1.7.10#182]
Thermal Foundation material textures probably changed in 1.7.10 They still look good but doesn't look the same as vanilla TF.
Needs updating:
CrystalCinnabar, DustBlizz, DustBronze, DustCoal, DustCopper, DustCryotheum, DustElectrum, DustEnderium, DustGold, DustInvar, DustIron, DustLead, DustNickel, DustNiter (mostly the same as vanilla but not completely), DustObsidian, DustPlatinum, DustSilver, DustTin, ingots and nuggets may need restyling too.

**Comment by Adaptivity** [comment]
Issue updated with more info. In my opinion Faithful textures more darker than originals. So, I think restyling is required.

**Comment by Evolution0** [comment]
If someone doesn't get to it before I do (I plan on Chisel being an ongoing thing while doing others) then I'll do it.

I know what you mean too, they added a bit more detail that had the side effect of lightening the textures (like the inner glow / iridescent effect on enderium)
