### ISSUE TITLE
[unfaithful texture] Biomes o Plenty Cherry Wood

### ISSUE THREAD

**Issue by p75369** [F32Organization/Faithful32-1.7.10#190]
The default colour is a deep red, but in the pack, it becomes more of a washed out pink.

**Comment by DZCreeper** [comment]
Sorry about that, it appears whoever started Biomes O' Plenty texturing didn't finish or needed more practice. I don't have time to match the colors exactly right now but the commit I just made should make it closer to the originals.

**Comment by p75369** [comment]
Thanks for that, though I just looked at the change, it also needs to be done to the planks too.
