### ISSUE TITLE
Reminder - New Thermal Expansion guis

### ISSUE THREAD

**Issue by EddyHg80** [F32Organization/Faithful32-1.7.10#201]
Just a reminder to check the new Thermal Expansion guis
Source: https://twitter.com/TeamCoFH/status/586936992392437760?s=09

**Comment by DZCreeper** [comment]
What update was this done on?

**Comment by EddyHg80** [comment]
I *think* on the latest release build on Curseforge, but I can't check because I'm not at home.

**Comment by Adaptivity** [comment]
Needs updating: Activator.png, Workbench.png(Schematic color), Slot_Output_Schematic.png (should be 64x64?), Tesseract.png, Assembler.png (Schematic color), Insolator.png, Smelter.png, Transposer.png.

**Comment by EddyHg80** [comment]
I updated the TODO for Thermal Expansion but I couldn't figure out what the tweet is talking about.
For now I'll close this issue.

**Comment by DZCreeper** [comment]
Turned out to be less complicated than I thought.

https://github.com/F32Organization/Faithful32-1.7.10/commit/6472d48250133f71928ebb593ce1d9ea90d4155a

Let me know if there is any more issues.
