### ISSUE TITLE
BC addon pipe textures are changed

### ISSUE THREAD

**Issue by Adaptivity** [F32Organization/Faithful32-1.7.10#211]
Additional Pipes:
Current: https://github.com/F32Organization/Faithful32-1.7.10/blob/master/assets/additionalpipes/textures/blocks/0.png
New: https://github.com/tcooc/AdditionalPipesBC/blob/master/src/main/resources/assets/additionalpipes/textures/blocks/0.png
ABO:
Current: https://github.com/F32Organization/Faithful32-1.7.10/blob/master/assets/additional-buildcraft-objects/textures/blocks/PipeItemsBounce.png
New: https://github.com/da3dsoul/Additional-Buildcraft-Objects/blob/1.7.10--BC6.3%2B/src/main/resources/assets/additional-buildcraft-objects/textures/blocks/PipeItemsBounce.png
Does this mean that they should be updated?

**Comment by DZCreeper** [comment]
Yeah, luckily the pipes are super easy to do. I will take a look at this today.

**Comment by DZCreeper** [comment]
Alright, going to close this for now. Let me know if there any remaining issues involving pipes.
