### ISSUE TITLE
Thermal expansion machines - displaced progress arrow 

### ISSUE THREAD

**Issue by HVK500** [F32Organization/Faithful32-1.7.10#251]

**Comment by DZCreeper** [comment]
Which version? This commit should have fixed them to match the latest version. https://github.com/F32Organization/Faithful32-1.7.10/commit/6472d48250133f71928ebb593ce1d9ea90d4155a

**Comment by HVK500** [comment]
The latest pack version, it seems that the referenced commit might be the cause of the problem.
(BTW: Thanks for your hard work) 
![dis-arr](https://cloud.githubusercontent.com/assets/5502187/7425404/7e0fe98e-efb0-11e4-9351-30425d109771.png)
![dis-arr2](https://cloud.githubusercontent.com/assets/5502187/7425405/7e176d4e-efb0-11e4-9d3e-c81bd328777b.png)

**Comment by DZCreeper** [comment]
I mean which version of Thermal Expansion and CoFHCore. The general rule that I try to follow is keep the textures up to date with the latest mod releases that aren't alpha versions.

**Comment by HVK500** [comment]
Oh I see, sorry I misunderstood. I just checked, the version I'm using is older. I just tested with a more recent version and is perfectly fine, Sorry for the mistake.
