### ISSUE TITLE
RotaryCraft V6f Missing Textures

### ISSUE THREAD

**Issue by TotalHamman** [F32Organization/Faithful32-1.7.10#279]
RotaryCraft V6f (current version) has added textures since last update to F32 textures.  A quick comparison of the items.png and items2.png between F32 and mod will show the missing textures.  

Thanks for all the great work you do!

**Comment by Evolution0** [comment]
Hmm not only that but it has been reorganized as well, seems the one currently in the pack was incomplete to begin with too.

Probably shouldn't have been merged or at least a copy should have been left in TODO.
