### ISSUE TITLE
[Ender IO] Capacitors textures too similiar!

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [F32Organization/Faithful32-1.7.10#299]
The capacitor textures are too similar in my opinion. It's hard to quickly distinguish between basic, double-layer, and octathingmajing capacitor.

**Comment by StefanTT** [comment]
Yes this is also my opinion. The old textures were better distinguishable.
Unfortunately this is how the original textures look now.

**Comment by StefanTT** [comment]
After some thinking ... I will try to improve the look of the different capacitors without breaking the original style.

**Comment by Xee1** [comment]
https://github.com/SleepyTrousers/EnderIO/commit/129ef251c103b5dbcb9ed864918efae114493f21
EnderIO changes the capacitor again.

**Comment by StefanTT** [comment]
Thanks, I did not notice that yet. I will adapt it to the new design when changing the capacitors.

**Comment by StefanTT** [comment]
Please have a look at my take on improving the capacitors: https://github.com/F32Organization/Faithful32-1.7.10/pull/302

**Comment by Unrepentant-Atheist** [comment]
Looks much better! Me likey!

**Comment by StefanTT** [comment]
I think this issue can be closed.
