### ISSUE TITLE
Ex Nihilo Ore Dust and Ore Sand textures are broken

### ISSUE THREAD

**Issue by 1skandar** [F32Organization/Faithful32-1.7.10#357]
I'm getting the purple/black checkerboard of doom.

**Comment by Evolution0** [comment]
Does it still happen with the texture pack disabled?

Because as far as I know when a texture isn't found in a resource pack it attempts to load it from the JAR of the mod itself, so in this case it could be broken in Ex Nihilo itself as we don't have those two done.

**Comment by 1skandar** [comment]
Nope, only within Faithful itself. 

The textures ARE there, btw. It is looking for IconSandTemplate, IconDustTemplate, and IconGravelTemplate for the ore gravels, sands, and dusts. The first two exist in Faithful and are broken, the Gravel one does not and is falling back to the mod textures like it is supposed to.

**Comment by DZCreeper** [comment]
For some reason the textures that were in the folder were all the same color but with varying alpha levels. Minecraft doesn't support alpha channel for regular solid blocks so that was probably the issue.

Either way, deleting them should at least let you use the default textures again.

**Comment by 1skandar** [comment]
Confirmed fixed in the latest version. Thanks.

**Comment by sirjaden92** [comment]
I've noticed in the latest update this error has occurred again. Ore dust & Ore sand are broken again.
