### ISSUE TITLE
New user questoins.

### ISSUE THREAD

**Issue by GamerM** [F32Organization/Faithful32-1.7.10#378]
1. What's the difference between TODO section and Assets? Do I just edit the TODO folder only or is it just showing what is needed to be done.

2. Is this using the textures from the Faithful mod support site or in sync with it? If so can I use textures from there and put it in here?

I'm a new user for this respiratory so I don't know how things goes here. Thanks!

**Comment by DZCreeper** [comment]
1. The TODO folder is for textures that haven't been done or need to be redone.

2. That depends on which site you mean. If you mean the legacy mod support, then no, it is not a mirror of that but I am sure we have some textures that have been reused from that era. If you mean www.f32.me then yes, it is kept in sync with the Github repositories.

**Comment by Iclario** [comment]
The file in the. TODO folder are the textures that have to be done. When you have edit it, just put it in his place in the asset folder.
I hope my explanation is clear.

**Comment by GamerM** [comment]
For question 2 I forgot to show the link to the site I was talking about. My bad.  (http://www.faithful32x32.com/modsupport.html). Anyways thanks! I will put some time into this at some point. I'll  mainly be focusing on IC2 and Buildcraft when starting off.

**Comment by Evolution0** [comment]
No as DZCreeper said that is an independent entity but we may have some reused textures. I'm not sure how updated it is either as you don't see Vattic often and the main thread is rarely updated.

Most of the time when someone makes mod support textures now they just get dumped in a post in the thread and forgotten and never make it onto the mod support page.

The workflow is pretty straight forward:
* fork *this repo*
* git clone *your fork*
* git remote add *this repo* upstream.

Then when you make changes to TODO textures move them (as in cut & paste) to their directory in assets and:
* git commit (Make clear sensible commit messages)
* git fetch upstream
* git rebase upstream/master
* git push.

At that point you can go to your fork and "make pull request".

These steps prevent you being behind or creating merge conflicts.

As a note to everyone else you may notice I've kind of dropped off the map, this doesn't mean I've stopped working on textures. At the moment I am in the process of a very long move which requires selling my house and getting plans together so it will be a while till I can start working on textures again. :disappointed:

**Comment by GamerM** [comment]
Thanks this really help me. Know what to do now.
