### ISSUE TITLE
Multiple instances of texture in the Buildcraft folders?

### ISSUE THREAD

**Issue by GamerM** [F32Organization/Faithful32-1.7.10#388]
Hello. I am looking through the buildcraft folders (buildcraft, core, energy, factory, robotics, silicon, and transport) and was trying to organize things out (#331). When i was looking through them i notice there are Multiple texture for one object? Both of these textures can be used for F32 and it is hard to make a decision. What should i do with these textures? 

A good example are the laser beams, but there are more.
 1. Faithful32-1.7.10\assets\buildcraft\textures\entities
2.  Faithful32-1.7.10\assets\buildcraftcore\textures\laserBeams

Also I'm also deleting moving textures from assets\buildcraft to their right module. There is no use for these texture beside the latest buildcraft right? Like there isn't like a "Buildcraft Classic".

Update: It is mainly Between the Builcraft Folder and the modules. I think someone made textures without knowing that that they are already textures inside the assets/buildcraft folder. Just like what i did.

**Comment by Evolution0** [comment]
No I was fully aware. You may not know but Pre-Buildcraft 6 (BC7 is fairly new, people still play 6) all textures were contained in a single Buildcraft folder, this however isn't the case with BC7 which uses separate folders for each module. (But luckily doesn't use the original Buildcraft assets folder)

The reason for having both is to retain compatibility with BC6 while also providing Faithful textures for BC7. That is why a lot of the textures look different; because they are.

This is intentional, leave it as it is.

**Comment by GamerM** [comment]
I see what you are saying about making it compatible with BC6 and BC7, but as of right now there are still some untexture items,blocks, etc if you are using BC7. I was thinking we should use the BC6 textures as a filler for BC7 textures for now. Later on I or anyone will edit those texture to make it more updated and have cleaner look. BC is one of the most use mods and can well be the thing that judges who will use the resource pack. I Rather have something there then nothing.

In a summary I would copy and paste textures to the right module then cut and paste. I will also edit most of the textures that aren't up to date with BC7 at the end anyway. Does this sound good?

**Comment by Evolution0** [comment]
We already moved over what textures could be used.

And that isn't how we go about texturing things, the only textures that should be in the BC7 folders are ones in faithful resolution that match the new style. All textures that aren't done should be in TODO and moved as they are completed.

This is for consistency and to avoid mistakes.

**Comment by GamerM** [comment]
I understand @Evolution0 how texturing works here and how the mod.jar has already the default texture in it. What i mean from untexture is how it is using the default textures then the one in F32 (aka the ones in the buildcraft folder). 

I never knew that you guys are making a new F32 style for BC7. Which made me think that you guys didn't move the texture right to the modules yet (#331 was open), and made me start moving them.

Also are you sure you move over all the textures you can use? The reason why i'm moving stuff around at the first place was because i was helping @DZCreeper move pipes (#386). Which is still in good condition and have the same style as the additionalpipes.

So i'll just say i'll help copy the pipes over to the right module for @DZCreeper (#386) and then leave everything else. Thanks Evolution0 for clearing things up.

**Comment by Evolution0** [comment]
Yeah some of the pipes are *maybe* usable, those are the only textures I didn't go over. Keep in mind though while they may at first glance look the same they may not be on closer inspection.

We had this problem early on where textures got copied over because they looked the same but they really weren't. (You have to zoom in, CyanideX did a palette change among other details in the new BC7 textures)

What you may not notice in a thumbnail is very noticeable in an image editor or in-game.

**Comment by GamerM** [comment]
Ahh i see (Do you know the issue or commit that discuss the problem?). Well to be honest i started inspection already on the pipes and i will be delighted to help you out.  They all seems to be ok, beside the occasional lighting problems between blocks. For the most part it is completely fine. I would say though that some texture should be redone entirely. An example would be how i made the cobblestone pipe have different shades then the one shown in the pictures. 

Take a look.
![2015-07-11_09 55 03](https://cloud.githubusercontent.com/assets/8530902/8633994/c3301238-27b3-11e5-8b46-550316dc9002.png)
![2015-07-11_09 54 35](https://cloud.githubusercontent.com/assets/8530902/8633989/c32c579c-27b3-11e5-917d-3a2120333b1f.png)
![2015-07-11_09 54 59](https://cloud.githubusercontent.com/assets/8530902/8633991/c32d62ae-27b3-11e5-8c24-61095baffd8d.png)
![2015-07-11_09 55 12](https://cloud.githubusercontent.com/assets/8530902/8633993/c33003ba-27b3-11e5-9303-a4addfd4d847.png)
![2015-07-11_09 55 15](https://cloud.githubusercontent.com/assets/8530902/8633995/c337e1ac-27b3-11e5-8c9c-fe29dadaed71.png)

I would say my self that these textures are still updated with the F32 style. Some of the pipes though i think will have to be redone. Like the stripes and cobble structure pipes (which will be move in the TODO list). There wasn't any issue with structure problems between the image and block. They did not change the template of pipes. I think i will be working on this soon ,and making a pull request later this week for this. 

going to close this issue probably today because it is already getting a little bit too long.
