### ISSUE TITLE
With The Faithful 32 - Modded Edition Texture Pack

### ISSUE THREAD

**Issue by LaLamborghini** [F32Organization/Faithful32-1.7.10#390]
With the broken items like broken iron ore, broken lead ore etc. and the crushed and powered items, the item is just a black box. Is there any known reason why its like this?

**Comment by Evolution0** [comment]
Mod name?

Would help the guys find the issue faster rather than searching thousands of textures.

**Comment by LaLamborghini** [comment]
thank you blocky-mcsquare
