### ISSUE TITLE
With The Faithful 32 - Modded Edition Texture Pack

### ISSUE THREAD

**Issue by LaLamborghini** [F32Organization/Faithful32-1.7.10#393]
With the broken items like broken iron ore, broken lead ore etc. and the crushed and powered items, the item is just a black box. Is there any known reason why its like this? Mod Name = Ex Nihlio

**Comment by Evolution0** [comment]
Don't create double issues just edit the one already open.

**Comment by DZCreeper** [comment]
Duplicate of #391
