### ISSUE TITLE
Nullifier UI misaligned

### ISSUE THREAD

**Issue by evilhamsterman** [F32Organization/Faithful32-1.7.10#405]
In Thermal Expansion 4.0.3B1 as included in Infinity 1.9.0 the Nullifier UI is misaligned
![screenshot from 2015-07-27 15-49-37](https://cloud.githubusercontent.com/assets/59560/8919807/5d1e4a84-3477-11e5-8edc-d771720e295d.png)

**Comment by Wolf68k** [comment]
Fixed in Pull #407

**Comment by evilhamsterman** [comment]
Looks like it is fixed 
![2015-07-28_18 01 33](https://cloud.githubusercontent.com/assets/59560/8947684/ba0ef6a4-3552-11e5-9ef7-9c03c028fd0a.png)
