### ISSUE TITLE
EnderIO Farming station GUI misaligned

### ISSUE THREAD

**Issue by evilhamsterman** [F32Organization/Faithful32-1.7.10#416]
In EnderIO 2.2.8.381 as included in Infinity 1.9.0 the Farming Station UI is misaligned

![2015-07-31_21 24 57](https://cloud.githubusercontent.com/assets/59560/9020599/4e245f1c-37cb-11e5-9fcc-6dded73f4422.png)

**Comment by evilhamsterman** [comment]
In fact it appears to be completely different then the UI that is used in the current version. Comparison to no resource pack
![2015-07-31_21 35 28](https://cloud.githubusercontent.com/assets/59560/9020618/244f3b34-37cc-11e5-81af-6fd2a7e87b4e.png)

**Comment by DZCreeper** [comment]
Something is wrong here. The farmStation.png from EnderIO was last changed on March 19. The latest version of Infinity should be using that texture. Perhaps visit the EnderIO repository and ask what is going on. https://github.com/SleepyTrousers/EnderIO/issues

March 19: Bonemeal slots added.

March 17: Apple and leave slots added.

February 23: Shear slot added.

https://github.com/SleepyTrousers/EnderIO/blob/master/resources/assets/enderio/textures/gui/farmStation.png

**Comment by Adaptivity** [comment]
I can easily explain this to you: Latest available *stable* version of Ender IO 2.2.8.381 doesn't have Bonemeal, Apple, Leaves, Shear slots. The latest texture in repository is for *unstable* incomplete Ender IO 2.3 which is still in development and have no set release date.

**Comment by DZCreeper** [comment]
Thank you very much for the information.

@evilhamsterman In your pull request to fix this please move the current farmStation.png to the folder I have created https://github.com/F32Organization/Faithful32-1.7.10/commit/53cdcda3d96560ff3034b3b55ff7e1a2fd419efe

When Ender IO 2.3 is released we will simply swap out the texture.

**Comment by StefanTT** [comment]
We could have an "unstable" branch of our repository for those changes.

**Comment by evilhamsterman** [comment]
I agree with @StefanTT the best way to handle this would be a separate branch. However for now I have rebased off of the master and copied the development version of the gui to the folder requested. Since PR #418 was locked I can't comment there.

**Comment by evilhamsterman** [comment]
It also appears that this texture has been "Fixed" and refixed several times because of this in commits 
f974011, 1a5da2e, and 6422b72. I don't think there is a consistency on whether the git repo is hosting textures for stable versions of mods or dev versions of the mods. Having a separate branch for dev/unstable versions of mods would be a good idea. The master branch would follow the stable released versions as exist in large packs like Infinity, Tekkit, etc. An unstable branch could work on prerelease/unstable versions of mods.

**Comment by DZCreeper** [comment]
@StefanTT That is the plan with the new folder I have created. People who want to do work on for unreleased mod versions can put that stuff in the DevModTextures folder.
