### ISSUE TITLE
Tinker Slab Furnace

### ISSUE THREAD

**Issue by nalkrien** [F32Organization/Faithful32-1.7.10#423]
I believe the tinker slab furnace is still using the buggy compressed version of the texture, it is showing up whitish in game.

**Comment by steveowashere** [comment]
Seems you are correct, 
For some reason or anything those textures are saved in Gray scale color mode, To fix this you can simply save the affected textures in RGB color mode with Photoshop. If you don't have PS or simply don't want to fix it yourself, I'll create a pull request to fix the affected textures. I just need to test and see if other textures are affected.
