### ISSUE TITLE
Do: Wood Stuff

### ISSUE THREAD

**Issue by Adaptivity** [F32Organization/Faithful32-1.7.10#444]
https://github.com/ganymedes01/WoodStuff/tree/master/src/main/resources/assets/woodstuff/textures It's just have texture templates. Should be easy enough.

**Comment by steveowashere** [comment]
Should be pretty simple, I'll try to include it in my commits along with Immersive Engineering tonight.

**Comment by Adaptivity** [comment]
Done. Thanks @steveowashere
