### ISSUE TITLE
Immersive Engineering Nickel Ore needs recoloring

### ISSUE THREAD

**Issue by Serifina** [F32Organization/Faithful32-1.7.10#448]
Immersive Engineering's nickel ore blends in much, much too well with stone, making it very, very easy to miss while mining. Could it be modified/recolored in some fashion to make it more noticeable?

http://i.imgur.com/XEM8iCT.png

**Comment by steveowashere** [comment]
When I made the texture, I didn't see there was shadows around the ore parts. So I fixed that and it looks something like this: 
![2015-09-02_08 53 36](https://cloud.githubusercontent.com/assets/13194819/9624795/6602cb98-5150-11e5-80c6-b1ddc415bd1e.png)

Original for comparison

![2015-09-02_08 54 03](https://cloud.githubusercontent.com/assets/13194819/9624796/6a9aa7ca-5150-11e5-8b41-3cafa5d4025a.png)

Hopefully that should be a bit more noticeable. 

I'll create a pull request to merge this change.

**Comment by Adaptivity** [comment]
@DZCreeper FYI, should be closed. @steveowashere you can automatically close issues without bothering @DZCreeper. It's simple Github magic.
Just do something like this:
Closes #(issue number)
Closes #(issue number)
and etc
Keep in mind that each issue number should have word "Closes" in front of it. If you do so, Github automatically close mentioned issues when PR will be merged.

**Comment by steveowashere** [comment]
Cool thanks @Adaptivity! 
Closes #448
