### ISSUE TITLE
[Request] Texture for the dev version of EnderIO's Vacuum Chest

### ISSUE THREAD

**Issue by mrammy** [F32Organization/Faithful32-1.7.10#462]
Currently looks like this ![](http://i.imgur.com/2VCeExA.png)

**Comment by steveowashere** [comment]
Generally speaking we don't do textures for dev/beta version of mods. We wait until full releases come out. (see #413). But I can try to update the GUI and add it to the DevModTextures folder. From there you can download it and manually add it to your pack if you want.

**Comment by mrammy** [comment]
That would be great thanks!

**Comment by steveowashere** [comment]
You can download it here: https://mega.nz/#!ihZHGT6T!Q1_Jur9uRtEemXcQSYKXDHBQTi07ytnAP0_SL2pPZI8

Otherwise I will add it to my next commit, that way others can check my work. However I did quickly test it and it looks good to me.

**Comment by Adaptivity** [comment]
@DZCreeper close this too.
