### ISSUE TITLE
Broken Aluminum Ingot Texture

### ISSUE THREAD

**Issue by WhichLilith** [F32Organization/Faithful32-1.7.10#466]
Hey there, I just want to let you know that in the last update (and already the one before, on September 18), the Tinker's Construct aluminum ingot texture is broken (back to low resolution). All other Tinker's ingots have a great look though. Anyway, you guys do a great job there, there is nothing better than Vattic's Faithful Modded Version :D Thanks so much for everything!

**Comment by Adaptivity** [comment]
@steveowashere removed this for some reason in https://github.com/F32Organization/Faithful32-1.7.10/commit/41d3a306db53821f64eaf75f1107d18220b1b4bc

**Comment by WhichLilith** [comment]
Hehehe, no problem. I just realized it yesterday, and thought to inform you guys as it seems just to be a little error (the other TC ingots look brilliant). Anyway, thanks a lot for the quick reply! And keep up the awesome work, many people appreciate what you are doing, and I cannot play MC without Faithful anymore :D

**Comment by steveowashere** [comment]
@Adaptivity Is right, i accidentally removed that text when doing Immersive Engineering's stuff, my bad. 

I'll make a commit to fix this. 

@WhichLilith Thanks for reporting the error, glad you're enjoying the pack.

**Comment by WhichLilith** [comment]
Thanks so much there! Glad I could help a bit there :D And it is more than just enjoying, I LOVE it :DDD
