### ISSUE TITLE
(Botania) Chiseled Livingrock Brick

### ISSUE THREAD

**Issue by Serifina** [F32Organization/Faithful32-1.7.10#475]
Chiseled Livingrock Brick looks nearly identical to regular Livingrock Brick. Was this a mistake somewhere?

http://imgur.com/a/DOX32 (Imgur album comparing the two blocks with and without the resource pack).

**Comment by steveowashere** [comment]
Seems to be two of the same textures (or similar texture) when they should be different. (livingrock01 and livingrock04)
Not sure if this in intentional because it was like this in older versions of Botania, or a mistake. 


I'll create a fix for this at any rate.
