### ISSUE TITLE
IC2 (GUISteamGenerator)

### ISSUE THREAD

**Issue by DocNeO** [F32Organization/Faithful32-1.7.10#478]
In general, I noticed that in the assembly "Faithful 32 Modded Edition" do not have all the textures, so I decided to help you with Gui IC2. So I draw Gui of the steam generator "Before" and "After"

![guisteamgenerator](https://cloud.githubusercontent.com/assets/15088044/10434289/4f30e97c-7121-11e5-8c87-337303093843.png) ![guisteamgenerator](https://cloud.githubusercontent.com/assets/15088044/10434248/15cb645a-7121-11e5-8db6-2e6690790d32.png)

**Comment by steveowashere** [comment]
Great work! 

Please submit a pull request to have this file added to the pack. You can find the instructions on the main page under 'Contributing:'. If you have any questions, just ask :)

**Comment by DocNeO** [comment]
The first time I am on the site, so I can not navigate, can help how to submit your file?)

**Comment by steveowashere** [comment]
Try to read everything under 'Contributing' 

https://github.com/F32Organization/Faithful32-1.7.10

You need git client: https://desktop.github.com/ (for Windows only)

**Comment by Xen1290** [comment]
@DZCreeper this can be closed.
