### ISSUE TITLE
Gui of IC2

### ISSUE THREAD

**Issue by DocNeO** [F32Organization/Faithful32-1.7.10#482]
GUIWaterKineticGenerator
![guiwaterkineticgenerator](https://cloud.githubusercontent.com/assets/15088044/10455345/65f72048-71c3-11e5-9a74-7f1c4cb7b6a6.png)
![guiwaterkineticgenerator](https://cloud.githubusercontent.com/assets/15088044/10455441/fb9bb74e-71c3-11e5-86ea-d02ccd859fd8.png)

GUIWindKineticGenerator
![guiwindkineticgenerator](https://cloud.githubusercontent.com/assets/15088044/10455349/6afee9b8-71c3-11e5-9590-ea69956ea7b6.png)
![guiwindkineticgenerator](https://cloud.githubusercontent.com/assets/15088044/10455405/ac33ba30-71c3-11e5-8df0-2b5cfd9b48ca.png)

**Comment by Evolution0** [comment]
If you are trying to contribute make a PR, this helps maintainers keep track as well as guarantees that you are credited.
