### ISSUE TITLE
Missing Texture: BC Transport - Quartz Transport Pipe

### ISSUE THREAD

**Issue by UristMcStoutHorn** [F32Organization/Faithful32-1.7.10#484]
Noticed when I swapped out some cobblestone to quartz pipes.  Seems there are Liquid/Power Quartz Pipe textures already though, from looking around in the pack zip.  Downloaded the newest one today to make sure I wasn't crazy (Last rebuild at the time was Oct 15).

**Comment by steveowashere** [comment]
Making a commit to fix this & add support for all BC pipes. I assume you're on BC 7 or higher?

**Comment by UristMcStoutHorn** [comment]
Yes sir.  Playing Regrowth which is currently using buildcraft-7.0.23.
Thanks for digging into this.
