### ISSUE TITLE
Magical Crops: Core, Armory, and Decorative

### ISSUE THREAD

**Issue by Boqzo1** [F32Organization/Faithful32-1.7.10#488]
Hi there! Is there any way that you could complete more of the textures for magical crops? I know the seeds are mostly done but none of the tools or armor or blocks are done. It would be greatly appreciated! Thanks!

**Comment by steveowashere** [comment]
I'll try to include a few of the tools and armor items in my next commit (Sunday). No promises on the blocks, those are normally pretty time consuming for me.

**Comment by Boqzo1** [comment]
Awesome! Thanks.

**Comment by steveowashere** [comment]
Made a pull request for a few of the items. Didn't have time to do the blocks, but I should get to them next week.
