### ISSUE TITLE
Ugly rendering caused by EnderIO/Blocks/FusedGlass

### ISSUE THREAD

**Issue by GunArm** [F32Organization/Faithful32-1.7.10#517]
I'm using 1.7.10.  

When I started using FaithfulME I noticed, aside from the textures, a certain ugly rendering efect that gnarles up ALL the textures.  It is especially noticable in leaves in the distance as you are moving.  Once you notice it, it is incredibly obvious and kinda terrible.  It's like really REALLY bad aliasing everywhere worse than normal.  I spent the last (wow) 6 hours bisecting the these resources, narrowed it to the Es, to enderio, blocks, then to fusedGlass.png CRC 0A093AF3

I know it sounds crazy that one small png could somehow cause rendering issues everywhere, but I have tested it backwards and forwards, alone and in the company of others.  
It is that file.... somehow.

The thing about reproducing this is, once it gets into the state where the textures (especially leaves) look "noisy" during movement, once it loads a resource that does that, it stays in that state until the client is restarted.  Thats why it took 6 hours of bisection to find it because I had to keep restarting my modded client every time the effect started.
So
1.  Start with NO resource packs during startup.
2.  Start your client (one with enderio so the textures will load)  
3.  For benchmark, look at some leaves in the distance, and see how they look as you move.  (smooth aside from regular aliasing)
4.  Add a resource pack with nothing but enderIO/Blocks/FusedGlass.png
5.  See how leaves in the distance are now gnarled up as you move.

I expect this is a bug in minecraft proper and somehow that file is exposing it.  Perhaps it could be re-exported as a png somehow to make it change some metadata or something and fix it.  If nothing else I think the resource pack would be better off without that one texture, than putting the whole client into this weird rendering state.

**Comment by GunArm** [comment]
Looking closer there's clearly something wrong with the file, the image is 1x1

**Comment by DZCreeper** [comment]
Does this happen without EnderIO? This type of bug should be impossible unless they are changing something deep in the rendering system.

**Comment by DZCreeper** [comment]
Let me know if that made an impact.

**Comment by GunArm** [comment]
With the new file:  fine

With the old file:
   Without EnderIO: fine
   With EnderIO: gnarled
--------------------

There could be similar issues with other mods I don't have and the textures aren't getting loaded, but, for me atleast, everything is great with the new image.

I would also have expected it to be impossible, but I was reproing it very consistently.  And the new file fixes it.  Thanks!  

FWIW, I have seen the effect before, Chromaticraft mod does it without any resource packs.  I had thought reika was using some sort of buggy shader or something creating the effect.  Now I am guessing there is a texture in the mod like this.

**Comment by ReikaKalseki** [comment]
CC has a 1x1 texture for one of its icons, yes, but I have never seen any issues of any kind, either before or after I made such a texture. I also have never seen anyone report it (the only issue being that FastCraft disables mipmapping when it detects it).

Can you record a video?

**Comment by Adraxas** [comment]
@GunArm do you have Fastcraft installed?

**Comment by GunArm** [comment]
I do have fastcraft installed.  Is it still worth me trying to record a video?

**Comment by DZCreeper** [comment]
If FastCraft is messing with mipmapping in an attempt to save resources then there is no point recording a video unless you wish to point it out to Player.

**Comment by ReikaKalseki** [comment]
> Edit: come to think of it, I have seen the effect in CC with nothing but vanilla and forge

And I have not, nor heard from anyone else who has.

**Comment by ReikaKalseki** [comment]
A GIF was posted to my thread. It is the FastCraft mipmapping issue. Relay this to Player.
