### ISSUE TITLE
Immersive engineering voltmeter icon and model messed up

### ISSUE THREAD

**Issue by escman1999** [F32Organization/Faithful32-1.7.10#521]
https://imgur.com/a/EMQgP

**Comment by StefanTT** [comment]
Its fine for at least immersive engineering 0.6.2
Its broken for immersive engineering 0.6.4

**Comment by escman1999** [comment]
can it be fixed for 0.6.4?

**Comment by StefanTT** [comment]
An option might be to remove the texture from the modpack for some weeks, as the name is the same but it is used for completely different things.

**Comment by escman1999** [comment]
i think that would be a good idea until it's fixed, because that's what's currently holding me back from using this resource pack

**Comment by StefanTT** [comment]
Well if it's only that, then open the ZIP with a zip-tool and remove the file
assets/immersiveengineering/textures/items/tool_voltmeter.png

**Comment by StefanTT** [comment]
@escman1999 could you please verify if my fix fixes the issue for you?

**Comment by escman1999** [comment]
._. i haven't used this resource pack in a long time

**Comment by StefanTT** [comment]
Ok, never mind, thanks for the feedback.
I think this issue can be closed (as it is fixed), but everybody is welcome to verify it.

**Comment by p75369** [comment]
Having experienced the problem before, I can confirm that the new texture works.

**Comment by StefanTT** [comment]
Great, thanks for testing!

@DZCreeper please close this issue
