### ISSUE TITLE
Glass icons invisibility

### ISSUE THREAD

**Issue by Andrey228322** [F32Organization/Faithful32-1.7.10#538]
glass icon is not visible. What to do? How to fix?

**Comment by StefanTT** [comment]
Please have a look at issue #396, its probably the same as your problem.
For me it makes a difference if I use GUI scale normal or auto.

**Comment by Andrey228322** [comment]
I see! And I can not understand the decision ...

**Comment by StefanTT** [comment]
This happens due to finer lines in Faithful than in standard minecraft textures. 

You will have the same issue on other texture packs too.
Its not a texture pack issue.
We cannot fix it.

**Comment by Andrey228322** [comment]
And is it possible to take a glass from the default Minecraft?

**Comment by StefanTT** [comment]
Sure.

You can also unzip the Faithful texture pack in your Minecraft's resourcepacks folder and remove those textures in there that you do not like. Or directly manipulate the zip file, whatever suits you.

**Comment by Andrey228322** [comment]
say pls name Texture Block glass. I find him

**Comment by StefanTT** [comment]
It depends on which glass blocks you mean, they are in different directories.
The vanilla glass is assets/minecraft/textures/blocks/glass.png

**Comment by DZCreeper** [comment]
This is a known issue that results from having anisotropic filtering turned on. On resolutions of 1920x1080 or smaller you will find that glass may render oddly in your inventory.
