### ISSUE TITLE
Draconium Ore Gravel Texture Missing

### ISSUE THREAD

**Issue by DJ411** [F32Organization/Faithful32-1.7.10#551]
I noticed that this block does not have a texture. Its a Purple and Black block atm. When i take the texture pack off it shows up. Hope this can be fixed.

Mod pack i'm playing is FTB SkyFactory 2.5.2 if that helps for testing.
Mod block is from is Ex Astris

**Comment by StefanTT** [comment]
F32 does not yet contain any Ex Astris textures, so it must be from some other mod.

**Comment by DJ411** [comment]
thanks for the response. I was actually gonna ask if someone can find what mod its coming from and hope its out there somewhere. Hopefully a request for the item can be made.

**Comment by StefanTT** [comment]
If the texture is missing in Faithful then the block has it's default 16x16 texture. When the block is black/pink checkered then it usually means that a texture in Faithful is broken, e.g. due to unsupported transparency. The other possible cause I have seen is that the texture is animated but the animation info file is missing in Faithful.

So or so, we need to find the location of the block's texture to fix it. Having a 2D snapshot of the texture (not of the block itself) would help, as we could then try our luck with image search.

**Comment by shadow306k** [comment]
I'd like to add that it also applies to nether/end versions of ore gravel blocks. 

I was just about to post a new issue for this, and it seems the problem stems from Ex Astris using Ex Nihilo's base template textures. Tested by removing Ex Nihilo from the resource pack, and the textures went back to their 16x versions and worked fine. I'm just not sure how to fix it in ex Nihilo.

**Comment by StefanTT** [comment]
Thanks for the hint, I will have another look tonight.

**Comment by shadow306k** [comment]
I'm playing around at the moment, and I've narrowed it down to being an issue in textures/blocks. I'll update this if I have anything else useful/found a fix

**Comment by StefanTT** [comment]
ok fine :+1:

**Comment by shadow306k** [comment]
Alright, it's two files causing the problem. IconGravelBaseEnder.png and IconGravelBaseNether.png

I tried just putting a plain white 32x png in there, and they went from the default 16x textures to MissingTexture

**Comment by shadow306k** [comment]
I FIXED IT!!! It's actually four files! 
[Here's an imgur link](http://imgur.com/hrgJvGI) which highlights the four files causing the problem, and my really bad fix for it using a recolour of the gravel texture. I'm no texture artist, so I can't make a texture for them, but I found what needs doing.

(I'm also bad at github so idk what to do from here.)

**Comment by StefanTT** [comment]
Ah, great, thanks for investigating!  :+1:
I will try to fix it tonight.

**Comment by StefanTT** [comment]
The gravel base textures for endstone and nether gravel were missing. I added them in the change, now it looks good for me in FTB skyblocks (before it was broken too).

**Comment by StefanTT** [comment]
The issue should be fixed now.
@DJ411 and/or @shadow306k can you verify it please?

**Comment by DJ411** [comment]
I now see it @StefanTT. Thank you.

**Comment by StefanTT** [comment]
Great, thanks for testing.

I think we can close the issue then, @DZCreeper
