### ISSUE TITLE
Crash with Fastcraft + wrong textures with IC2 Classic

### ISSUE THREAD

**Issue by Jules06** [F32Organization/Faithful32-1.7.10#556]
Hi, I keep crashing when I try to switch to the F32 texture pack :(
Here's the crash report : http://pastebin.com/7TWhRvV4 .
I know that I can fix this by removing fastcraft but i get mad lags without it, so is there a way to use both the ressource pack and fastcraft? Thanks

**Comment by Xen1290** [comment]
java.lang.RuntimeException: Can't fit all textures, use lower resolution texture packs or remove mods.

**Comment by StefanTT** [comment]
I have no problems here in the mod packs that contain fastcraft and even optifine.

If I have problems than it's with mod packs that are unstable by themselves. Those packs tend to sometimes fail to start or make problems when e.g. enabling optifine.

In other words: I second Xen1290's opinion, I think we cannot help you here.

**Comment by Jules06** [comment]
Too bad, I'll have to use the default texture pack :(
 Thanks anyway!

**Comment by Xen1290** [comment]
@Jules06 maybe you can ask help in the fastcraft tread.
