### ISSUE TITLE
Railcraft Coupler Track Auto-Coupler Mode

### ISSUE THREAD

**Issue by bballboy2002** [F32Organization/Faithful32-1.7.10#563]
![screen shot 2016-11-13 at 3 12 21 pm](https://cloud.githubusercontent.com/assets/14823057/20246668/9760478a-a9b3-11e6-9257-2787554c346f.png)

**Comment by bballboy2002** [comment]
Fix ![track coupler](https://cloud.githubusercontent.com/assets/14823057/20246913/177a7382-a9b9-11e6-8073-198887525180.png)

**Comment by StefanTT** [comment]
:+1:
