### ISSUE TITLE
[Bug] Project Red, certain tiles are not displaying properly

### ISSUE THREAD

**Issue by ranger135xp** [F32Organization/Faithful32-1.7.10#568]
You will find a good chunk of information here: https://github.com/MrTJP/ProjectRed/issues/1080

**Comment by MrTJP** [comment]
Solution: In the projectred/integration/surface directory, only include the following four textures, altered as per the texture pack:
- base.png
- bordermatte.png
- wirematte-OFF.png
- wirematte-ON.png

The other icons in that folder are not actually textures, simply helper data files used for gate wire path generation which are frequently changed and causes issues when older files are loaded through texture packs.

**Comment by ranger135xp** [comment]
I can confirm through working with MrTJP, that once those files were removed from F32's pack, everything worked perfectly. I followed the exact instructions above.

**Comment by StefanTT** [comment]
I will create a pull request with these textures removed. As the original textures are 32x32 it does not make sense to have them in the texture pack anyways. A quick check in game does not show any visible difference if they are removed or not. Of course :-)

**Comment by StefanTT** [comment]
My change is meanwhile merged, please have a look if it fixes the problem for you (it should).
If you are happy with the fix then please close this issue - I do not have the permissions to close it.

**Comment by ranger135xp** [comment]
@StefanTT I got an email that you updated this thread, but the update is not posted here. Did you apply the fix to the pack?

**Comment by StefanTT** [comment]
It is in commit ad55e58 which was merged yesterday.

**Comment by Iclario** [comment]
Fixed by https://github.com/F32Organization/Faithful32-1.7.10/commit/ad55e5812022decccd1cb41144eb1316850810d9
