### ISSUE TITLE
Wrong color in MEDense_Gray.png

### ISSUE THREAD

**Issue by SapientMC** [F32Organization/Faithful32-1.7.10#569]
assets\appliedenergistics2\textures\blocks\MEDense_Gray.png
is same as assets\appliedenergistics2\textures\blocks\MEDense_Green.png
Should be different i think.

**Comment by StefanTT** [comment]
Indeed. Funny that nobody noticed this yet.

**Comment by StefanTT** [comment]
@SapientMC please test, the issue should be fixed by now.

**Comment by SapientMC** [comment]
@StefanTT I confirm. Now all fine. Thanx a lot :)
