### ISSUE TITLE
"www.f32.me/mods" stupidly broken

### ISSUE THREAD

**Issue by nexfwall** [F32Organization/Faithful32-1.7.10#577]
It's sad, guys, but it looks like you forgot about the `>` in the end of the PHP script... And it's seems to be a long time since this shi^W was happened.

But at least, I've tried to draw your attention to this.

![image](https://user-images.githubusercontent.com/8678891/27405384-035782d6-56da-11e7-8585-d1bdbd64f40f.png)

**Comment by DZCreeper** [comment]
The PHP for that sub-folder isn't working at all, I forgot to enable it after the web server accidentally got defaulted during an in-place OS upgrade. It wasn't really doing anything besides making the page look a little better so I will just let Apache handle it.

The whole folder needs an update but I haven't and likely won't find the time to get involved in anything Minecraft related again.
