### ISSUE TITLE
Chisel cobblestone

### ISSUE THREAD

**Issue by Alleluid** [F32Organization/Faithful32-1.7.10#87]
Posted here at your request DZ.

**Comment by Xee1** [comment]
What? XyCraft is out? Where?

**Comment by DZCreeper** [comment]
No, the latest Chisel added its own XyCraft style blocks. I am going to take care of them today but I was too tired last night so I asked Alleluid to leave me this reminder.

**Comment by Xee1** [comment]
Oh, in fact, it seemed strange that was out!

**Comment by DZCreeper** [comment]
Reminder to self, check out what needs changing: http://www.curse.com/mc-mods/minecraft/225236-chisel-2/download

**Comment by Evolution0** [comment]
As far as I know the cobblestone has been done. Might want to close this.

Unless its a reminder to work on chisel textures in general, then id change the title.

**Comment by Xen1290** [comment]
@DZCreeper this can be closed, also the new chisel is here:
http://minecraft.curseforge.com/mc-mods/235279-chisel
