### ISSUE TITLE
Question about GT

### ISSUE THREAD

**Issue by Xee1** [F32Organization/Faithful32-1.7.10#89]
I'm checking the folder of GT, and I noticed that the gui are without G yellow. There is any problem if I add it?
Now:
![1by1](https://cloud.githubusercontent.com/assets/8685029/5790819/196cf2e8-9eab-11e4-9c2a-fcd36230dd35.png)
Later:
![1by1](https://cloud.githubusercontent.com/assets/8685029/5790835/b9964076-9eab-11e4-935e-458364b7fd96.png)
Original from jar:
![1by1](https://cloud.githubusercontent.com/assets/8685029/5790836/c6ccba90-9eab-11e4-8772-02c84d5e86ca.png)

@Iclario @DZCreeper

**Comment by DZCreeper** [comment]
Not a problem in my opinion but if you want to fix it go ahead.

**Comment by Xee1** [comment]
Perfect, I'll go ahead !

**Comment by Xee1** [comment]
Other question @DZCreeper , @Iclario , GT 1.7.10 is completely different from 1.6, so, I keep old textures? If you check my work in progress for GT go on my fork. Once I finish I'll merge on the main repository.

**Comment by DZCreeper** [comment]
Could you word that differently, its hard to understand. If you mean keep the 1.6 textures in the 1.7 version, don't bother unless they are still used. We don't bother maintaining backwards compatibility, that's why there are different version of the pack download.

**Comment by Xee1** [comment]
Oh sorry, for different I mean no longer used, most of texture now are made with grayscale for example, this I meant. I'll delete it, thanks.

**Comment by DZCreeper** [comment]
Closed by https://github.com/F32Organization/Faithful32-1.7.10/commit/e209fc64cc51c7c77cd2eb53c965479df3820536

Make a new issue if there are additional Gregtech problems.
