### ISSUE TITLE
Fixed Reactorcraft Ores

### ISSUE THREAD

**Issue by The-Order** [F32Organization/Faithful32-1.7.10#96]
I fixed the Reactorcraft ores from looking blurry (finally). Not sure how to use this github thing nor could I figure it out so I hope this google drive link works.

https://drive.google.com/file/d/0B0XbQ0OpHz_3ckNXZHhaekhUdms/view?usp=sharing

**Comment by DZCreeper** [comment]
Github works pretty simply, you fork the repository, clone it locally to your computer using a Github client, push the local changes to the online repository, and then submit those changes as a pull request. If its too much of a bother don't worry about it, it only takes me a couple minutes at most to add this stuff manually.

Added in https://github.com/F32Organization/Faithful32-1.7.10/commit/3836536c4c6ae3241597d940ae94bd15ca2d9ef9
